import { ArrowUpDown, ExternalLink, PackageOpen } from 'lucide-react';
import { useState } from 'react';
import type { Product } from '../types/product';

export function ResultsTable({ products }: { products: Product[] }) {
  const [filter, setFilter] = useState(''); const [sortAsc, setSortAsc] = useState(true);
  const shown = products.filter((item) => `${item.product_name} ${item.brand ?? ''} ${item.platform}`.toLowerCase().includes(filter.toLowerCase())).sort((a, b) => ((a.selling_price ?? Infinity) - (b.selling_price ?? Infinity)) * (sortAsc ? 1 : -1));
  if (!products.length) return <div className="empty"><PackageOpen size={32} /><h3>No products yet</h3><p>Run a search to populate this table.</p></div>;
  return <section className="results-section"><div className="table-toolbar"><div><span className="eyebrow">Listings</span><h2>{products.length} products found</h2></div><input aria-label="Filter results" value={filter} onChange={(event) => setFilter(event.target.value)} placeholder="Filter results" /></div><div className="table-wrap"><table><thead><tr><th>Product</th><th>Source</th><th><button className="sort-button" onClick={() => setSortAsc(!sortAsc)}>Price <ArrowUpDown size={13} /></button></th><th>MRP / discount</th><th>Availability</th><th>Pack</th><th /></tr></thead><tbody>{shown.map((product, index) => <tr key={`${product.platform}-${product.product_name}-${index}`}><td><strong>{product.product_name}</strong><small>{product.brand ?? 'Independent listing'}</small></td><td><span className={`platform ${product.platform}`}>{product.platform}</span></td><td className="price">{product.selling_price == null ? '—' : `₹${product.selling_price.toFixed(2)}`}</td><td>{product.mrp == null ? '—' : `₹${product.mrp.toFixed(2)}`}<small className="discount">{product.discount ? `${product.discount}% off` : 'No offer'}</small></td><td><span className="availability">{product.availability ?? 'Unknown'}</span></td><td>{product.pack_size ?? '—'}</td><td>{product.product_url && <a href={product.product_url} target="_blank" rel="noreferrer" aria-label={`Open ${product.product_name}`}><ExternalLink size={16} /></a>}</td></tr>)}</tbody></table></div></section>;
}
